"""create permissions tables

Revision ID: 1f30147b4dea
Revises: bfed0d9b8dbb
Create Date: 2026-03-23 21:42:26.709338
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1f30147b4dea'
down_revision = 'bfed0d9b8dbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=False)

    op.create_table('job_title_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles.id'], name=op.f('fk_job_title_permissions_job_title_id_job_titles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_job_title_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_title_permissions')),
    sa.UniqueConstraint('job_title_id', 'permission_id', name='uq_job_title_permissions_job_title_permission')
    )
    with op.batch_alter_table('job_title_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_title_permissions_job_title_id'), ['job_title_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title_permissions_permission_id'), ['permission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_title_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_title_permissions_permission_id'))
        batch_op.drop_index(batch_op.f('ix_job_title_permissions_job_title_id'))

    op.drop_table('job_title_permissions')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.drop_index(batch_op.f('ix_permissions_module'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
