"""create requests engine tables

Revision ID: 5c8eac3602ed
Revises: 1f30147b4dea
Create Date: 2026-03-23 22:04:58.088369
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5c8eac3602ed'
down_revision = '1f30147b4dea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_types'))
    )
    with op.batch_alter_table('request_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_request_types_name'), ['name'], unique=False)

    op.create_table('request_type_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], name=op.f('fk_request_type_fields_request_type_id_request_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_type_fields')),
    sa.UniqueConstraint('request_type_id', 'code', name='uq_request_type_fields_request_type_code')
    )
    with op.batch_alter_table('request_type_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_type_fields_request_type_id'), ['request_type_id'], unique=False)

    op.create_table('request_workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('step_kind', sa.String(length=20), nullable=False),
    sa.Column('resolver_type', sa.String(length=50), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], name=op.f('fk_request_workflow_steps_request_type_id_request_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_workflow_steps')),
    sa.UniqueConstraint('request_type_id', 'step_order', name='uq_request_workflow_steps_request_type_step_order')
    )
    with op.batch_alter_table('request_workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_workflow_steps_request_type_id'), ['request_type_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_type_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('requester_employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('current_approver_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_approver_user_id'], ['users.id'], name=op.f('fk_requests_current_approver_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_step_id'], ['request_workflow_steps.id'], name=op.f('fk_requests_current_step_id_request_workflow_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_type_id'], ['request_types.id'], name=op.f('fk_requests_request_type_id_request_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_employee_id'], ['employees.id'], name=op.f('fk_requests_requester_employee_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name=op.f('fk_requests_requester_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_current_approver_user_id'), ['current_approver_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_current_step_id'), ['current_step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_request_type_id'), ['request_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_requester_employee_id'), ['requester_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_requester_user_id'), ['requester_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)

    op.create_table('request_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=120), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('step_kind', sa.String(length=20), nullable=True),
    sa.Column('resolver_type', sa.String(length=50), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_request_actions_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_actions_request_id_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['request_workflow_steps.id'], name=op.f('fk_request_actions_step_id_request_workflow_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_actions'))
    )
    with op.batch_alter_table('request_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_actions_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_actions_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_actions_step_id'), ['step_id'], unique=False)

    op.create_table('request_field_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_field_id', sa.Integer(), nullable=True),
    sa.Column('field_code', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_field_id'], ['request_type_fields.id'], name=op.f('fk_request_field_values_request_field_id_request_type_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_field_values_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_field_values')),
    sa.UniqueConstraint('request_id', 'field_code', name='uq_request_field_values_request_field_code')
    )
    with op.batch_alter_table('request_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_field_values_request_field_id'), ['request_field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_field_values_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_field_values_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_field_values_request_field_id'))

    op.drop_table('request_field_values')
    with op.batch_alter_table('request_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_actions_step_id'))
        batch_op.drop_index(batch_op.f('ix_request_actions_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_actions_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_actions_action'))

    op.drop_table('request_actions')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_requester_user_id'))
        batch_op.drop_index(batch_op.f('ix_requests_requester_employee_id'))
        batch_op.drop_index(batch_op.f('ix_requests_request_type_id'))
        batch_op.drop_index(batch_op.f('ix_requests_current_step_id'))
        batch_op.drop_index(batch_op.f('ix_requests_current_approver_user_id'))

    op.drop_table('requests')
    with op.batch_alter_table('request_workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_workflow_steps_request_type_id'))

    op.drop_table('request_workflow_steps')
    with op.batch_alter_table('request_type_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_type_fields_request_type_id'))

    op.drop_table('request_type_fields')
    with op.batch_alter_table('request_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_types_name'))
        batch_op.drop_index(batch_op.f('ix_request_types_code'))

    op.drop_table('request_types')
    # ### end Alembic commands ###
