"""create organization tables

Revision ID: 845f896ebe24
Revises: dfccf269ad7b
Create Date: 2026-03-23 21:18:24.290113
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '845f896ebe24'
down_revision = 'dfccf269ad7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hierarchical_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hierarchical_level >= 0', name=op.f('ck_job_titles_hierarchical_level_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_titles'))
    )
    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_titles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_titles_name'), ['name'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_departments_manager_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_manager_user_id'), ['manager_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('leader_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_teams_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], name=op.f('fk_teams_leader_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_teams_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_leader_user_id'), ['leader_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_leader_user_id'))
        batch_op.drop_index(batch_op.f('ix_teams_department_id'))
        batch_op.drop_index(batch_op.f('ix_teams_code'))

    op.drop_table('teams')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_manager_user_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('job_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_titles_name'))
        batch_op.drop_index(batch_op.f('ix_job_titles_code'))

    op.drop_table('job_titles')
    # ### end Alembic commands ###
