from __future__ import annotations

LEGACY_PERMISSION_ALIASES: dict[str, str] = {
    "organization.read": "organization.view",
    "organization.read_hierarchy": "organization.hierarchy.view",
    "organization.company_hierarchy": "organization.hierarchy.view_all",
    "employees.read": "employees.view",
    "permissions.read": "permissions.view",
    "announcements.read": "announcements.view",
    "messages.read": "messages.view",
    "messages.read_users": "messages.recipients.view",
    "messages.templates": "messages.templates.manage",
    "requests.read": "requests.view",
    "requests.read_all": "requests.view_all",
    "requests.read_my_approvals": "requests.approvals.view",
    "attendance.read": "attendance.view",
    "performance.read": "performance.view",
    "dashboard.read": "dashboard.view",
    "dashboard.analytics.read": "dashboard.analytics.view",
    "create_requests": "requests.create",
    "manage_requests": "requests.manage",
}


CANONICAL_JOB_TITLES = (
    {
        "key": "super_admin",
        "code": "SUPER_ADMIN",
        "name": "Super Admin",
        "description": "Platform owner with unrestricted administrative access.",
        "hierarchical_level": 7,
    },
    {
        "key": "rh_manager",
        "code": "RH_MANAGER",
        "name": "HR Manager",
        "description": "Owns HR operations, approvals, and cross-company people workflows.",
        "hierarchical_level": 6,
    },
    {
        "key": "hr_assistant",
        "code": "HR_ASSISTANT",
        "name": "HR Assistant",
        "description": "Supports HR operations, employee administration, and NFC card assignment.",
        "hierarchical_level": 5,
    },
    {
        "key": "attendance_manager",
        "code": "ATTENDANCE_MANAGER",
        "name": "Attendance Manager",
        "description": "Maintains attendance ingestion, NFC enrollment, and reporting operations.",
        "hierarchical_level": 5,
    },
    {
        "key": "finance_payroll",
        "code": "FINANCE_PAYROLL",
        "name": "Finance / Payroll",
        "description": "Consumes workforce and attendance data for payroll preparation.",
        "hierarchical_level": 5,
    },
    {
        "key": "department_manager",
        "code": "DEPARTMENT_MANAGER",
        "name": "Department Manager",
        "description": "Manages departmental approvals, visibility, and operational follow-up.",
        "hierarchical_level": 4,
    },
    {
        "key": "team_leader",
        "code": "TEAM_LEADER",
        "name": "Team Leader",
        "description": "Leads one team and handles first-line approvals and performance updates.",
        "hierarchical_level": 3,
    },
    {
        "key": "employee",
        "code": "EMPLOYEE",
        "name": "Employee",
        "description": "Standard employee profile for daily HR self-service operations.",
        "hierarchical_level": 1,
    },
)


CANONICAL_PERMISSIONS = (
    {
        "code": "organization.view",
        "name": "View organization",
        "description": "View departments, teams, and job titles.",
        "module": "organization",
    },
    {
        "code": "organization.hierarchy.view",
        "name": "View organization hierarchy",
        "description": "View hierarchy trees scoped to the current user.",
        "module": "organization",
    },
    {
        "code": "organization.hierarchy.view_all",
        "name": "View full company hierarchy",
        "description": "View the full company organigram and hierarchy tree.",
        "module": "organization",
    },
    {
        "code": "organization.create",
        "name": "Create organization records",
        "description": "Create departments, teams, and job titles.",
        "module": "organization",
    },
    {
        "code": "organization.update",
        "name": "Update organization records",
        "description": "Update departments, teams, and job titles.",
        "module": "organization",
    },
    {
        "code": "organization.deactivate",
        "name": "Deactivate organization records",
        "description": "Deactivate departments, teams, and job titles.",
        "module": "organization",
    },
    {
        "code": "employees.view",
        "name": "View employees",
        "description": "View employee profiles.",
        "module": "employees",
    },
    {
        "code": "employees.create",
        "name": "Create employees",
        "description": "Create employee profiles and linked accounts.",
        "module": "employees",
    },
    {
        "code": "employees.update",
        "name": "Update employees",
        "description": "Update employee profiles and linked accounts.",
        "module": "employees",
    },
    {
        "code": "permissions.view",
        "name": "View permissions",
        "description": "View permission catalog entries and job-title assignments.",
        "module": "permissions",
    },
    {
        "code": "permissions.create",
        "name": "Create permissions",
        "description": "Create new permission catalog entries.",
        "module": "permissions",
    },
    {
        "code": "permissions.update",
        "name": "Update permissions",
        "description": "Update permission catalog entries.",
        "module": "permissions",
    },
    {
        "code": "permissions.assign",
        "name": "Assign permissions",
        "description": "Replace permission sets assigned to job titles.",
        "module": "permissions",
    },
    {
        "code": "announcements.view",
        "name": "View announcements",
        "description": "Read company-wide announcements visible to the current user.",
        "module": "announcements",
    },
    {
        "code": "announcements.create",
        "name": "Create announcements",
        "description": "Create company-wide announcements.",
        "module": "announcements",
    },
    {
        "code": "announcements.update",
        "name": "Update announcements",
        "description": "Update company-wide announcements and their attachments.",
        "module": "announcements",
    },
    {
        "code": "announcements.delete",
        "name": "Delete announcements",
        "description": "Delete company-wide announcements by deactivating them.",
        "module": "announcements",
    },
    {
        "code": "messages.view",
        "name": "View messages",
        "description": "Read inbox and sent internal messages.",
        "module": "messages",
    },
    {
        "code": "messages.recipients.view",
        "name": "View message recipients",
        "description": "List users available for message composition.",
        "module": "messages",
    },
    {
        "code": "messages.send_all",
        "name": "Send messages to anyone",
        "description": "Compose messages to any active user.",
        "module": "messages",
    },
    {
        "code": "messages.send_same_or_down",
        "name": "Send messages to same or lower levels",
        "description": "Compose messages only to users on the same hierarchy level or below.",
        "module": "messages",
    },
    {
        "code": "messages.reply",
        "name": "Reply to message threads",
        "description": "Reply inside accessible message conversations.",
        "module": "messages",
    },
    {
        "code": "messages.templates.manage",
        "name": "Manage message templates",
        "description": "Create, update, and delete personal message templates.",
        "module": "messages",
    },
    {
        "code": "messages.send",
        "name": "Send messages (legacy)",
        "description": "Legacy send permission kept for backward compatibility.",
        "module": "messages",
    },
    {
        "code": "requests.view",
        "name": "View requests",
        "description": "Read request records visible to the current user.",
        "module": "requests",
    },
    {
        "code": "requests.create",
        "name": "Create requests",
        "description": "Submit new workflow requests.",
        "module": "requests",
    },
    {
        "code": "requests.approve",
        "name": "Approve requests",
        "description": "Approve or reject the current request step assigned to the user.",
        "module": "requests",
    },
    {
        "code": "requests.approvals.view",
        "name": "View my approval history",
        "description": "Read approval or rejection actions personally performed by the current user.",
        "module": "requests",
    },
    {
        "code": "requests.manage",
        "name": "Manage request configuration",
        "description": "Manage request types, request fields, and workflow steps.",
        "module": "requests",
    },
    {
        "code": "requests.view_all",
        "name": "View all requests",
        "description": "Read all requests without visibility restrictions.",
        "module": "requests",
    },
    {
        "code": "attendance.view",
        "name": "View attendance",
        "description": "Read attendance daily summaries and monthly reports.",
        "module": "attendance",
    },
    {
        "code": "attendance.ingest",
        "name": "Ingest attendance events",
        "description": "Submit external attendance scan events.",
        "module": "attendance",
    },
    {
        "code": "attendance.nfc.ingest",
        "name": "Ingest NFC attendance events",
        "description": "Submit NFC scan events from the dedicated scanner application.",
        "module": "attendance",
    },
    {
        "code": "attendance.nfc.view_cards",
        "name": "View NFC card inventory",
        "description": "View NFC card inventory including temporary provisional cards.",
        "module": "attendance",
    },
    {
        "code": "attendance.nfc.assign_card",
        "name": "Assign NFC cards",
        "description": "Attach NFC cards to employees for attendance identification.",
        "module": "attendance",
    },
    {
        "code": "attendance.reports.generate",
        "name": "Generate attendance reports",
        "description": "Generate monthly attendance reports from daily summaries.",
        "module": "attendance",
    },
    {
        "code": "performance.view",
        "name": "View performance",
        "description": "Read team performance records.",
        "module": "performance",
    },
    {
        "code": "performance.create",
        "name": "Create performance records",
        "description": "Submit daily team performance records.",
        "module": "performance",
    },
    {
        "code": "performance.manage",
        "name": "Manage performance objectives",
        "description": "Manage team performance objectives and view all team performance.",
        "module": "performance",
    },
    {
        "code": "dashboard.view",
        "name": "View dashboard",
        "description": "Access dashboard and reporting endpoints within the permitted scope.",
        "module": "dashboard",
    },
    {
        "code": "dashboard.manage",
        "name": "Manage dashboard scope",
        "description": "Access dashboard data without scope restrictions.",
        "module": "dashboard",
    },
    {
        "code": "dashboard.analytics.view",
        "name": "View dashboard analytics",
        "description": "View dashboard analytics widgets and summaries.",
        "module": "dashboard",
    },
    {
        "code": "profile.view",
        "name": "View profile",
        "description": "View user profile information.",
        "module": "profile",
    },
    {
        "code": "admin_panel.access",
        "name": "Access admin panel",
        "description": "Reserved permission entry for the internal control panel catalog.",
        "module": "admin_panel",
    },
    {
        "code": "employees.view_contract_type",
        "name": "View employee contract types",
        "description": "View contract type and external company information for employees.",
        "module": "employees",
    },
    {
        "code": "employees.update_contract_type",
        "name": "Update employee contract types",
        "description": "Update contract type and external company for employees.",
        "module": "employees",
    },
    {
        "code": "forgot_badge.create",
        "name": "Create forgot badge requests",
        "description": "Create and cancel own forgot badge requests.",
        "module": "forgot_badge",
    },
    {
        "code": "forgot_badge.view_own",
        "name": "View own forgot badge requests",
        "description": "View the current user's own forgot badge requests.",
        "module": "forgot_badge",
    },
    {
        "code": "forgot_badge.view_all",
        "name": "View all forgot badge requests",
        "description": "View all forgot badge requests in the organization.",
        "module": "forgot_badge",
    },
    {
        "code": "forgot_badge.manage",
        "name": "Manage forgot badge requests",
        "description": "Approve, reject, complete, and manage forgot badge requests.",
        "module": "forgot_badge",
    },
    {
        "code": "attendance.nfc.assign_temporary_card",
        "name": "Assign temporary NFC cards",
        "description": "Assign temporary NFC cards for forgot badge scenarios.",
        "module": "attendance",
    },
    {
        "code": "attendance.nfc.release_temporary_card",
        "name": "Release temporary NFC cards",
        "description": "Manually release temporary NFC card assignments.",
        "module": "attendance",
    },
)


ROLE_PERMISSION_MATRIX: dict[str, list[str]] = {
    "SUPER_ADMIN": [definition["code"] for definition in CANONICAL_PERMISSIONS],
    "RH_MANAGER": [
        "organization.view",
        "organization.hierarchy.view",
        "organization.hierarchy.view_all",
        "organization.create",
        "organization.update",
        "organization.deactivate",
        "employees.view",
        "employees.create",
        "employees.update",
        "employees.view_contract_type",
        "employees.update_contract_type",
        "permissions.view",
        "permissions.create",
        "permissions.update",
        "permissions.assign",
        "announcements.view",
        "announcements.create",
        "announcements.update",
        "announcements.delete",
        "messages.view",
        "messages.recipients.view",
        "messages.send_all",
        "messages.reply",
        "messages.templates.manage",
        "requests.view",
        "requests.create",
        "requests.approve",
        "requests.approvals.view",
        "requests.manage",
        "requests.view_all",
        "attendance.view",
        "attendance.ingest",
        "attendance.nfc.ingest",
        "attendance.nfc.view_cards",
        "attendance.nfc.assign_card",
        "attendance.nfc.assign_temporary_card",
        "attendance.nfc.release_temporary_card",
        "attendance.reports.generate",
        "performance.view",
        "performance.manage",
        "dashboard.view",
        "dashboard.analytics.view",
        "profile.view",
        "forgot_badge.create",
        "forgot_badge.view_own",
        "forgot_badge.view_all",
        "forgot_badge.manage",
    ],
    "HR_ASSISTANT": [
        "organization.view",
        "organization.hierarchy.view",
        "employees.view",
        "employees.create",
        "employees.update",
        "employees.view_contract_type",
        "announcements.view",
        "announcements.create",
        "announcements.update",
        "messages.view",
        "messages.recipients.view",
        "messages.send_same_or_down",
        "messages.reply",
        "requests.view",
        "requests.create",
        "attendance.view",
        "attendance.nfc.view_cards",
        "attendance.nfc.assign_card",
        "attendance.nfc.assign_temporary_card",
        "attendance.nfc.release_temporary_card",
        "forgot_badge.create",
        "forgot_badge.view_own",
        "forgot_badge.view_all",
        "forgot_badge.manage",
        "dashboard.view",
        "profile.view",
    ],
    "ATTENDANCE_MANAGER": [
        "organization.view",
        "employees.view",
        "employees.view_contract_type",
        "announcements.view",
        "messages.view",
        "messages.recipients.view",
        "messages.send_same_or_down",
        "messages.reply",
        "requests.view",
        "attendance.view",
        "attendance.ingest",
        "attendance.nfc.ingest",
        "attendance.nfc.view_cards",
        "attendance.nfc.assign_card",
        "attendance.nfc.assign_temporary_card",
        "attendance.nfc.release_temporary_card",
        "attendance.reports.generate",
        "forgot_badge.view_all",
        "forgot_badge.manage",
        "dashboard.view",
        "dashboard.analytics.view",
        "profile.view",
    ],
    "FINANCE_PAYROLL": [
        "organization.view",
        "employees.view",
        "employees.view_contract_type",
        "announcements.view",
        "messages.view",
        "messages.recipients.view",
        "messages.send_same_or_down",
        "messages.reply",
        "requests.view",
        "attendance.view",
        "attendance.reports.generate",
        "dashboard.view",
        "dashboard.analytics.view",
        "profile.view",
    ],
    "DEPARTMENT_MANAGER": [
        "organization.view",
        "organization.hierarchy.view",
        "employees.view",
        "employees.view_contract_type",
        "announcements.view",
        "messages.view",
        "messages.recipients.view",
        "messages.send_same_or_down",
        "messages.reply",
        "requests.view",
        "requests.create",
        "requests.approve",
        "requests.approvals.view",
        "attendance.view",
        "performance.view",
        "forgot_badge.view_own",
        "forgot_badge.view_all",
        "dashboard.view",
        "profile.view",
    ],
    "TEAM_LEADER": [
        "organization.hierarchy.view",
        "announcements.view",
        "messages.view",
        "messages.recipients.view",
        "messages.send_same_or_down",
        "messages.reply",
        "requests.view",
        "requests.create",
        "requests.approve",
        "requests.approvals.view",
        "attendance.view",
        "performance.create",
        "performance.view",
        "forgot_badge.view_own",
        "dashboard.view",
        "profile.view",
    ],
    "EMPLOYEE": [
        "announcements.view",
        "messages.view",
        "messages.recipients.view",
        "messages.send_same_or_down",
        "messages.reply",
        "requests.create",
        "requests.view",
        "attendance.view",
        "forgot_badge.create",
        "forgot_badge.view_own",
        "dashboard.view",
        "profile.view",
    ],
}
